
CREATE TABLE Address (id INTEGER CONSTRAINT PK_ADDRESS PRIMARY KEY AUTOINCREMENT NOT NULL, street TEXT NOT NULL, street_number TEXT);

CREATE TABLE Person (id INTEGER CONSTRAINT PK_PERSON PRIMARY KEY AUTOINCREMENT NOT NULL, foo TEXT, name TEXT NOT NULL, age INTEGER);

CREATE TABLE foo (wolf TEXT);

