CREATE TABLE Address (id INTEGER CONSTRAINT PK_ADDRESS PRIMARY KEY AUTOINCREMENT NOT NULL, street TEXT, city TEXT NOT NULL);

CREATE TABLE Person (id INTEGER CONSTRAINT PK_PERSON PRIMARY KEY AUTOINCREMENT NOT NULL, name TEXT NOT NULL, age INTEGER, address_id INTEGER);

CREATE TABLE foo (wolf TEXT);

