/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_sqlite_jni_capi_SQLTester */

#ifndef _Included_org_sqlite_jni_capi_SQLTester
#define _Included_org_sqlite_jni_capi_SQLTester
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_sqlite_jni_capi_SQLTester
 * Method:    strglob
 * Signature: ([B[B)I
 */
JNIEXPORT jint JNICALL Java_org_sqlite_jni_capi_SQLTester_strglob
  (JNIEnv *, jclass, jbyteArray, jbyteArray);

/*
 * Class:     org_sqlite_jni_capi_SQLTester
 * Method:    installCustomExtensions
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_sqlite_jni_capi_SQLTester_installCustomExtensions
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
