/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_sqlite_jni_fts5_fts5_tokenizer */

#ifndef _Included_org_sqlite_jni_fts5_fts5_tokenizer
#define _Included_org_sqlite_jni_fts5_fts5_tokenizer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_sqlite_jni_fts5_fts5_tokenizer
 * Method:    xTokenize
 * Signature: (Lorg/sqlite/jni/fts5/Fts5Tokenizer;I[BLorg/sqlite/jni/fts5/XTokenizeCallback;)I
 */
JNIEXPORT jint JNICALL Java_org_sqlite_jni_fts5_fts5_1tokenizer_xTokenize
  (JNIEnv *, jobject, jobject, jint, jbyteArray, jobject);

#ifdef __cplusplus
}
#endif
#endif
