/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_sqlite_jni_fts5_fts5_api */

#ifndef _Included_org_sqlite_jni_fts5_fts5_api
#define _Included_org_sqlite_jni_fts5_fts5_api
#ifdef __cplusplus
extern "C" {
#endif
#undef org_sqlite_jni_fts5_fts5_api_iVersion
#define org_sqlite_jni_fts5_fts5_api_iVersion 2L
/*
 * Class:     org_sqlite_jni_fts5_fts5_api
 * Method:    getInstanceForDb
 * Signature: (Lorg/sqlite/jni/capi/sqlite3;)Lorg/sqlite/jni/fts5/fts5_api;
 */
JNIEXPORT jobject JNICALL Java_org_sqlite_jni_fts5_fts5_1api_getInstanceForDb
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_sqlite_jni_fts5_fts5_api
 * Method:    xCreateFunction
 * Signature: (Ljava/lang/String;Ljava/lang/Object;Lorg/sqlite/jni/fts5/fts5_extension_function;)I
 */
JNIEXPORT jint JNICALL Java_org_sqlite_jni_fts5_fts5_1api_xCreateFunction
  (JNIEnv *, jobject, jstring, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
