/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_sqlite_jni_fts5_Fts5ExtensionApi */

#ifndef _Included_org_sqlite_jni_fts5_Fts5ExtensionApi
#define _Included_org_sqlite_jni_fts5_Fts5ExtensionApi
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_sqlite_jni_fts5_Fts5ExtensionApi
 * Method:    getInstance
 * Signature: ()Lorg/sqlite/jni/fts5/Fts5ExtensionApi;
 */
JNIEXPORT jobject JNICALL Java_org_sqlite_jni_fts5_Fts5ExtensionApi_getInstance
  (JNIEnv *, jclass);

/*
 * Class:     org_sqlite_jni_fts5_Fts5ExtensionApi
 * Method:    xColumnCount
 * Signature: (Lorg/sqlite/jni/fts5/Fts5Context;)I
 */
JNIEXPORT jint JNICALL Java_org_sqlite_jni_fts5_Fts5ExtensionApi_xColumnCount
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_sqlite_jni_fts5_Fts5ExtensionApi
 * Method:    xColumnSize
 * Signature: (Lorg/sqlite/jni/fts5/Fts5Context;ILorg/sqlite/jni/capi/OutputPointer/Int32;)I
 */
JNIEXPORT jint JNICALL Java_org_sqlite_jni_fts5_Fts5ExtensionApi_xColumnSize
  (JNIEnv *, jobject, jobject, jint, jobject);

/*
 * Class:     org_sqlite_jni_fts5_Fts5ExtensionApi
 * Method:    xColumnText
 * Signature: (Lorg/sqlite/jni/fts5/Fts5Context;ILorg/sqlite/jni/capi/OutputPointer/String;)I
 */
JNIEXPORT jint JNICALL Java_org_sqlite_jni_fts5_Fts5ExtensionApi_xColumnText
  (JNIEnv *, jobject, jobject, jint, jobject);

/*
 * Class:     org_sqlite_jni_fts5_Fts5ExtensionApi
 * Method:    xColumnTotalSize
 * Signature: (Lorg/sqlite/jni/fts5/Fts5Context;ILorg/sqlite/jni/capi/OutputPointer/Int64;)I
 */
JNIEXPORT jint JNICALL Java_org_sqlite_jni_fts5_Fts5ExtensionApi_xColumnTotalSize
  (JNIEnv *, jobject, jobject, jint, jobject);

/*
 * Class:     org_sqlite_jni_fts5_Fts5ExtensionApi
 * Method:    xGetAuxdata
 * Signature: (Lorg/sqlite/jni/fts5/Fts5Context;Z)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_org_sqlite_jni_fts5_Fts5ExtensionApi_xGetAuxdata
  (JNIEnv *, jobject, jobject, jboolean);

/*
 * Class:     org_sqlite_jni_fts5_Fts5ExtensionApi
 * Method:    xInst
 * Signature: (Lorg/sqlite/jni/fts5/Fts5Context;ILorg/sqlite/jni/capi/OutputPointer/Int32;Lorg/sqlite/jni/capi/OutputPointer/Int32;Lorg/sqlite/jni/capi/OutputPointer/Int32;)I
 */
JNIEXPORT jint JNICALL Java_org_sqlite_jni_fts5_Fts5ExtensionApi_xInst
  (JNIEnv *, jobject, jobject, jint, jobject, jobject, jobject);

/*
 * Class:     org_sqlite_jni_fts5_Fts5ExtensionApi
 * Method:    xInstCount
 * Signature: (Lorg/sqlite/jni/fts5/Fts5Context;Lorg/sqlite/jni/capi/OutputPointer/Int32;)I
 */
JNIEXPORT jint JNICALL Java_org_sqlite_jni_fts5_Fts5ExtensionApi_xInstCount
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     org_sqlite_jni_fts5_Fts5ExtensionApi
 * Method:    xPhraseCount
 * Signature: (Lorg/sqlite/jni/fts5/Fts5Context;)I
 */
JNIEXPORT jint JNICALL Java_org_sqlite_jni_fts5_Fts5ExtensionApi_xPhraseCount
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_sqlite_jni_fts5_Fts5ExtensionApi
 * Method:    xPhraseFirst
 * Signature: (Lorg/sqlite/jni/fts5/Fts5Context;ILorg/sqlite/jni/fts5/Fts5PhraseIter;Lorg/sqlite/jni/capi/OutputPointer/Int32;Lorg/sqlite/jni/capi/OutputPointer/Int32;)I
 */
JNIEXPORT jint JNICALL Java_org_sqlite_jni_fts5_Fts5ExtensionApi_xPhraseFirst
  (JNIEnv *, jobject, jobject, jint, jobject, jobject, jobject);

/*
 * Class:     org_sqlite_jni_fts5_Fts5ExtensionApi
 * Method:    xPhraseFirstColumn
 * Signature: (Lorg/sqlite/jni/fts5/Fts5Context;ILorg/sqlite/jni/fts5/Fts5PhraseIter;Lorg/sqlite/jni/capi/OutputPointer/Int32;)I
 */
JNIEXPORT jint JNICALL Java_org_sqlite_jni_fts5_Fts5ExtensionApi_xPhraseFirstColumn
  (JNIEnv *, jobject, jobject, jint, jobject, jobject);

/*
 * Class:     org_sqlite_jni_fts5_Fts5ExtensionApi
 * Method:    xPhraseNext
 * Signature: (Lorg/sqlite/jni/fts5/Fts5Context;Lorg/sqlite/jni/fts5/Fts5PhraseIter;Lorg/sqlite/jni/capi/OutputPointer/Int32;Lorg/sqlite/jni/capi/OutputPointer/Int32;)V
 */
JNIEXPORT void JNICALL Java_org_sqlite_jni_fts5_Fts5ExtensionApi_xPhraseNext
  (JNIEnv *, jobject, jobject, jobject, jobject, jobject);

/*
 * Class:     org_sqlite_jni_fts5_Fts5ExtensionApi
 * Method:    xPhraseNextColumn
 * Signature: (Lorg/sqlite/jni/fts5/Fts5Context;Lorg/sqlite/jni/fts5/Fts5PhraseIter;Lorg/sqlite/jni/capi/OutputPointer/Int32;)V
 */
JNIEXPORT void JNICALL Java_org_sqlite_jni_fts5_Fts5ExtensionApi_xPhraseNextColumn
  (JNIEnv *, jobject, jobject, jobject, jobject);

/*
 * Class:     org_sqlite_jni_fts5_Fts5ExtensionApi
 * Method:    xPhraseSize
 * Signature: (Lorg/sqlite/jni/fts5/Fts5Context;I)I
 */
JNIEXPORT jint JNICALL Java_org_sqlite_jni_fts5_Fts5ExtensionApi_xPhraseSize
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     org_sqlite_jni_fts5_Fts5ExtensionApi
 * Method:    xQueryPhrase
 * Signature: (Lorg/sqlite/jni/fts5/Fts5Context;ILorg/sqlite/jni/fts5/Fts5ExtensionApi/XQueryPhraseCallback;)I
 */
JNIEXPORT jint JNICALL Java_org_sqlite_jni_fts5_Fts5ExtensionApi_xQueryPhrase
  (JNIEnv *, jobject, jobject, jint, jobject);

/*
 * Class:     org_sqlite_jni_fts5_Fts5ExtensionApi
 * Method:    xRowCount
 * Signature: (Lorg/sqlite/jni/fts5/Fts5Context;Lorg/sqlite/jni/capi/OutputPointer/Int64;)I
 */
JNIEXPORT jint JNICALL Java_org_sqlite_jni_fts5_Fts5ExtensionApi_xRowCount
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     org_sqlite_jni_fts5_Fts5ExtensionApi
 * Method:    xRowid
 * Signature: (Lorg/sqlite/jni/fts5/Fts5Context;)J
 */
JNIEXPORT jlong JNICALL Java_org_sqlite_jni_fts5_Fts5ExtensionApi_xRowid
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_sqlite_jni_fts5_Fts5ExtensionApi
 * Method:    xSetAuxdata
 * Signature: (Lorg/sqlite/jni/fts5/Fts5Context;Ljava/lang/Object;)I
 */
JNIEXPORT jint JNICALL Java_org_sqlite_jni_fts5_Fts5ExtensionApi_xSetAuxdata
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     org_sqlite_jni_fts5_Fts5ExtensionApi
 * Method:    xTokenize
 * Signature: (Lorg/sqlite/jni/fts5/Fts5Context;[BLorg/sqlite/jni/fts5/XTokenizeCallback;)I
 */
JNIEXPORT jint JNICALL Java_org_sqlite_jni_fts5_Fts5ExtensionApi_xTokenize
  (JNIEnv *, jobject, jobject, jbyteArray, jobject);

/*
 * Class:     org_sqlite_jni_fts5_Fts5ExtensionApi
 * Method:    xUserData
 * Signature: (Lorg/sqlite/jni/fts5/Fts5Context;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_org_sqlite_jni_fts5_Fts5ExtensionApi_xUserData
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
