version: '3'
services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./configs/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"

  litefs-primary:
    build:
      context: .
      args:
        - "LITEFS_CONFIG=configs/litefs.docker.yml"
    privileged: true
    volumes:
      - litefs-storage-primary:/var/lib/litefs
    ports:
    - "8081:8080"
    - "20202:20202"
    environment:
      IS_PRIMARY: "true"
      ADVERTISE_URL: "http://litefs-primary:20202"
      DATABASE_URL: "jdbc:sqlite:/litefs/kicks.db?foreign_keys=ON"
      AUTHN_AUDIENCES: "localhost"
      AUTHN_ISSUER_URL: "http://localhost:3000"
      AUTHN_ADMIN_URL: "http://authn:3001"
      AUTHN_ADMIN_USERNAME: "admin"
      AUTHN_ADMIN_PASSWORD: "admin"

  litefs-replica1:
    build:
      context: .
      args:
        - "LITEFS_CONFIG=configs/litefs.docker.yml"
    privileged: true
    volumes:
      - litefs-storage-replica1:/var/lib/litefs
    ports:
    - "8082:8080"
    - "20203:20202"
    environment:
      IS_PRIMARY: "false"
      ADVERTISE_URL: "http://litefs-primary:20202"
      DATABASE_URL: "jdbc:sqlite:/litefs/kicks.db?foreign_keys=ON"
      AUTHN_AUDIENCE: "localhost"
      AUTHN_ISSUER_URL: "http://localhost:3000"
      AUTHN_ADMIN_URL: "http://authn:3001"
      AUTHN_ADMIN_USERNAME: "admin"
      AUTHN_ADMIN_PASSWORD: "admin"

  authn:
    image: keratin/authn-server:latest
    ports:
      - "3000:3000"
      - "3001:3001"
    volumes:
      - authn-data:/data
    environment:
      APP_DOMAINS: "localhost"
      AUTHN_URL: "http://localhost:3000"
      PORT: 3001
      PUBLIC_PORT: 3000
      SECRET_KEY_BASE: "test"
      DATABASE_URL: "sqlite3://localhost//data/authn.db"
    command: |
      sh -c "./authn migrate && ./authn server"

volumes:
  litefs-storage-primary:
  litefs-storage-replica1:
  authn-data:
