version: '3'
services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"

  litefs-primary:
    build:
      context: .
      args:
        - "LITEFS_CONFIG=litefs.docker.yml"
    volumes:
      - litefs-storage-primary:/var/lib/litefs
    ports:
    - "8081:8080"
    - "20202:20202"
    privileged: true
    environment:
      FLY_REGION: litefs-primary
      IS_PRIMARY: "true"
      ADVERTISE_URL: "http://litefs-primary:20202"

  litefs-replica1:
    build:
      context: .
      args:
        - "LITEFS_CONFIG=litefs.docker.yml"
    volumes:
      - litefs-storage-replica1:/var/lib/litefs
    ports:
    - "8082:8080"
    - "20203:20202"
    privileged: true
    environment:
      FLY_REGION: litefs-replica1
      IS_PRIMARY: "false"
      ADVERTISE_URL: "http://litefs-primary:20202"

volumes:
  litefs-storage-primary:
  litefs-storage-replica1:
