version: '3'
services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./configs/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"

  litefs-primary:
    build:
      context: .
      args:
        - "LITEFS_CONFIG=configs/litefs.docker.yml"
    privileged: true
    volumes:
      - litefs-storage-primary:/var/lib/litefs
    ports:
    - "8081:8080"
    - "20202:20202"
    environment:
      IS_PRIMARY: "true"
      ADVERTISE_URL: "http://litefs-primary:20202"
      DATABASE_URL: "jdbc:sqlite:/litefs/kicks.db?foreign_keys=ON"

  litefs-replica1:
    build:
      context: .
      args:
        - "LITEFS_CONFIG=configs/litefs.docker.yml"
    privileged: true
    volumes:
      - litefs-storage-replica1:/var/lib/litefs
    ports:
    - "8082:8080"
    - "20203:20202"
    environment:
      IS_PRIMARY: "false"
      ADVERTISE_URL: "http://litefs-primary:20202"
      DATABASE_URL: "jdbc:sqlite:/litefs/kicks.db?foreign_keys=ON"

  authelia:
    image: authelia/authelia
    container_name: authelia
    volumes:
      - ./authelia:/config
    networks:
      - net
    ports:
      - "9091:9091"
    expose:
      - 9091
    restart: unless-stopped
    healthcheck:
      ## In production the healthcheck section should be commented.
      disable: true
    environment:
      - TZ=Europe/Paris

volumes:
  litefs-storage-primary:
  litefs-storage-replica1:
