fuse:
  dir: "/litefs"

data:
  dir: "/var/lib/litefs"

lease:
  type: "static"
  advertise-url: $ADVERTISE_URL
  candidate: $IS_PRIMARY

# proxy:
#   addr: ":8080"
#   target: "localhost:8080"
#   db: "db"
#   passthrough:
#     - "*.ico"
#     - "*.png"

exec:
  - cmd: "java -jar httpServer.jar migrate-and-run"
    if-candidate: true
  - cmd: "java -jar httpServer.jar run"
    if-candidate: false
  - cmd: ln -s /litefs/kicks.db /app/ && litestream replicate
