name: Build
on:
  push:
    branches: ["master"]
  pull_request:
    types: [ opened, synchronize ]
  workflow_dispatch:

# automatically cancel previous runs on the same PR
# https://stackoverflow.com/questions/66335225/how-to-cancel-previous-runs-in-the-pr-when-you-push-new-commitsupdate-the-curre/67939898#67939898
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - uses: coursier/cache-action@v6

      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'yarn'
          cache-dependency-path: '**/yarn.lock'

      - name: Cache Scalablytyped transpilations
        uses: actions/cache@v3
        with:
          path: |
            ~/.ivy2/local/org.scalablytyped
            ~/.cache/scalablytyped
          key: ${{ runner.os }}-scalablytyped-${{ hashfiles('project/plugins.sbt') }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-scalablytyped-

      - name: load envrc
        uses: HatsuneMiku3939/direnv-action@v1

      - name: Yarn install
        run: |
          cd projects/webapp
          yarn install --frozen-lockfile

      - name: Compile and Test
        run: |
          ENABLE_FATAL_WARNINGS=true sbt --mem 4096 test scalafmtCheck scalafmtSbtCheck

      # - name: Run development web server
      #   run: |
      #     cd projects/webapp
      #     yarn run dev

      # - name: Cypress run (UI tests)
      #   uses: cypress-io/github-action@v6.6.0

      # - name: Debug over SSH (tmate)
      #   # if: ${{ failure() }}
      #   uses: mxschmitt/action-tmate@v3
      #   with:
      #     limit-access-to-actor: true
